default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: my_db_dev

test:
  <<: *default
  database: my_db_test

production:
  <<: *default
  database: my_db_prod
